Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -60,6 +60,10 @@ on:
         required: false
         default: 'false'
 
+defaults:
+  run:
+    shell: bash --noprofile --rcfile <(echo "$WF_RUN_SETUP") -eo pipefail {0}
+
 jobs:
   CI:
     runs-on: ubuntu-latest
@@ -84,7 +88,7 @@ jobs:
           STEP_CTX_GITHUB:  ${{ toJson(github) }}
           STEP_CTX_RUNNER:  ${{ toJson(runner) }}
         run: |
-          source <(echo "$WF_RUN_SETUP")
+          #source <(echo "$WF_RUN_SETUP")
           echo {'"github"':"$STEP_CTX_GITHUB"} | jq 'del(.github.token)|del(.github.event)' | flattenJson | toGroup 'github without event'
           echo "$STEP_CTX_GITHUB" | jq '{"github.event":.event}' | flattenJson | toGroup 'github.event'
           echo {'"runner"':"$STEP_CTX_RUNNER"} | flattenJson | toGroup 'runner'
@@ -132,6 +136,3 @@ jobs:
           docker image inspect ${{ env.STEP_IMG }} | flattenJson | toGroup 'inspect'
           docker image inspect ${{ env.STEP_IMG }} | jq -Mcr | toOutput 'json'
 
-      - run: |
-          source <(echo "$WF_RUN_SETUP")
-          echo '${{ steps.inspect.outputs.json }}' | toGroup steps.inspect.outputs.json
